Form metrics
luisbisp/desafio-backend pull request #2
Opened 2024-11-22 19:55 UTC by luisbisp

Adicionando as métricas de tempo no formulário

2024-11-25 17:00 UTC, fernandosaguirre commented on app/Http/Controllers/AnswerController.php
> +			$updateTimeMetric->updateFormTime($answer);
```suggestion
			(new MetricsService())->updateFormTime($answer);
```

Como você está manipulando uma única coisa, acredito que pode fazer dessa forma. Só estilo, nada errado como tu fez.

2024-11-25 17:02 UTC, fernandosaguirre commented on app/Http/Controllers/FormController.php
> +			'show_time_to_complete' => 'nullable|boolean',
pq a opção de aceitar um null aqui?

2024-11-25 17:09 UTC, fernandosaguirre commented on app/Http/Controllers/FormController.php
> +		$form->show_time_to_complete = (bool) $form->show_time_to_complete;
```suggestion
			$form->time_to_complete = $form->show_time_to_complete ? $form->getTimetoComplete() : null;
```

Acredito que tu poderia simplificar esse dado para uma linha se:
- Retornar um simples null caso esteja desativado
- abstrair a lógica do cálculo para o seu próprio método. Isso também ajuda a refatorar esse cálculo no futuro se for preciso.

2024-11-25 17:11 UTC, fernandosaguirre commented on app/Services/MetricsService.php
> +        $end = Carbon::parse($answer->respondent->completed_at);
isso não vai quebrar se completed_at for null?

2024-11-25 17:31 UTC, fernandosaguirre commented on app/Services/MetricsService.php
> +        $end = Carbon::parse($answer->respondent->completed_at);
Além disso, eu acho que `$answer->respondent` vai fazer 2 consultas no banco (depende se answer já contem esse dado, o que acho que não). 

Você poderia evitar isso armazenando o respondent em uma variável, ou melhor ainda, enviando esse dado em vez de Answer do controller. No controller você já sabe quem é o respondent, não precisa fazer essa query novamente.

2024-11-25 17:38 UTC, fernandosaguirre commented on database/migrations/2024_11_21_120023_create_form_metrics_table.php
> +            $table->string('total_time')->default(0);
isso não deveria ser um integer?

2024-11-25 17:49 UTC, fernandosaguirre commented on tests/Feature/FormTest.php
> +		$this->assertEquals(200, $response->json()['time_to_complete']);
```suggestion

$total_respondents = 5;
$total_time = 1000;
$expected_result = $total_time / $total_respondents ;
		$this->assertEquals($expected_result, $response->json()['time_to_complete']);
```

Normalmente é uma boa prática evitar "números mágicos", sem contexto.

2024-11-25 17:50 UTC, fernandosaguirre commented on tests/Feature/FormTest.php
> +		// dd($response->json());
lembra de limpar o código sempre :)

2024-11-25 17:51 UTC, fernandosaguirre commented on tests/Feature/FormTest.php
> +		$response->assertJson($form->toArray());
Esses asserts já foram testados no teste anterior, aqui tu deveria te preocupar só em garantir que o dado não foi exibido.

2024-11-25 17:53 UTC, fernandosaguirre commented on tests/Feature/MetricsTest.php
> +			]
Esses dados não tem relação com o teste. Se são obrigatórios, devem vir da factory. Se não são, não precisam estar aqui.

2024-11-25 17:54 UTC, fernandosaguirre commented on tests/Feature/MetricsTest.php
> +        $this->assertNotNull($post['data']['respondent']);
Esse assert não tem relação com o teste. Já deve ter sido previsto em um teste de answer/respondent

2024-11-25 17:55 UTC, fernandosaguirre commented on tests/Feature/MetricsTest.php
> +            'total_time' => 180,
Magic number :)

2024-11-25 17:57 UTC, fernandosaguirre commented on tests/Feature/MetricsTest.php
> +        ]);
Esse eu quebraria em um segundo teste, até pra ficar mais claro caso esse teste dê falha. Assim pelo titulo tu já sabe qual parte falhou.

2024-11-25 17:58 UTC, fernandosaguirre requested changes
Comentários pontuais.

2024-11-25 18:16 UTC, luisbisp commented on app/Http/Controllers/FormController.php
> +			'show_time_to_complete' => 'nullable|boolean',
Não quis deixar ele obrigátorio para criar um novo formulário, caso ele não seja enviado, por default o banco irá registrar como "false"

2024-11-26 18:49 UTC, fernandosaguirre commented on tests/Feature/FormTest.php
> +		$this->assertEquals($expectedResult, $response->json()['time_to_complete']);
```suggestion
		$this->assertEquals($expectedResult, $response->time_to_complete);
```

Acredito que tu pode acessar diretamente esse dado.

2024-11-26 19:05 UTC, fernandosaguirre approved these changes

2024-11-26 19:06 UTC, merged